trigger:
- main

pool:
  vmImage: ubuntu-latest

  steps:
  - script: echo Hello,we're provisioning k8s in my Azure subscription!
    displayName: run a one-line script

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'az-pub.pem'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendAzureRmSubscriptionId: 'dd8095e2-79de-47a1-ae9f-a45c751c3e0c'
    ensureBackend: true
    backendAzureRmStorageAccountName: 'storageaccountfordevzyx'
    backendAzureRmContainerName: 'mauricacontainerdev'
    backendAzureRmKey: 'akskeyfor.dev'
    allowTelemetryCollection: true



