trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- script: echo Hello, we're provisioning AKS in my Azure subscription!
  displayName: 'Run a one-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$()'
    backendType: 'azurerm'
    backendAzureRmSubscriptionId: 'dd8095e2-79de-47a1-ae9f-a45c751c3e0c'
    ensureBackend: true
    backendAzureRmStorageAccountName: 'storageaccountfordevENV'
    backendAzureRmContainerName: 'mauricacontainerDev'
    backendAzureRmKey: 'aksKeyfor.dev'
    allowTelemetryCollection: true



